promtail:
  daemonset:
    enabled: true

  defaultVolumes:
    - name: run
      hostPath:
        path: /run/promtail
    - name: containers
      hostPath:
        path: /var/lib/docker/containers
    - name: pods
      hostPath:
        path: /var/log/pods

  defaultVolumeMounts:
    - name: run
      mountPath: /run/promtail
    - name: containers
      mountPath: /var/lib/docker/containers
      readOnly: true
    - name: pods
      mountPath: /var/log/pods
      readOnly: true

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  tolerations:
    - operator: Exists

  securityContext:
    runAsUser: 0
    runAsGroup: 0

  config:
    serverPort: 9080

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    positions:
      filename: /run/promtail/positions.yaml

    scrapeConfigs:
      - job_name: kubernetes-pods
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: node_name
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - __meta_kubernetes_pod_label_app
            target_label: app
            regex: ^;*([^;]+)(;.*)?$
          - source_labels:
              - __meta_kubernetes_pod_label_app_kubernetes_io_instance
            target_label: instance
