---
- name: Check SSH configuration
  ansible.builtin.command: grep PermitRootLogin /etc/ssh/sshd_config
  register: ssh_config
  changed_when: false
  ignore_errors: true

- name: Check if passwords are required for sudo
  ansible.builtin.command: grep NOPASSWD /etc/sudoers
  register: sudo_config
  changed_when: false
  ignore_errors: true

- name: Get installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Check for unnecessary packages
  ansible.builtin.debug:
    msg: "Package {{ item }} is installed"
  when: item in ansible_facts.packages
  loop:
    - telnet
    - ftp
    - rsh

- name: Check open ports
  ansible.builtin.command: ss -tuln
  register: open_ports
  changed_when: false

- name: Generate security report
  ansible.builtin.debug:
    msg:
      - "Security Check Report for {{ inventory_hostname }}"
      - "SSH Root Login: {{ 'Disabled' if 'PermitRootLogin no' in ssh_config.stdout else 'Enabled' }}"
      - "Sudo Password: {{ 'Not Required' if sudo_config.rc == 0 else 'Required' }}"
      - "Open Ports:"
      - "{{ open_ports.stdout_lines }}"
