apiVersion: v2
name: monitoring
description: Monitoring Stack Helm chart (Prometheus, Grafana, AlertManager)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 55.5.0