nameOverride: monitoring
fullnameOverride: monitoring

prometheus:
  nameOverride: monitoring
  fullnameOverride: monitoring-prometheus
  server:
    fullnameOverride: monitoring-prometheus-server
    persistentVolume:
      enabled: true
      size: 4Gi
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

  alertmanager:
    enabled: true
    fullnameOverride: monitoring-alertmanager
    persistentVolume:
      enabled: true
      size: 2Gi
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

grafana:
  nameOverride: monitoring
  fullnameOverride: monitoring-grafana
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  persistence:
    enabled: true
    size: 5Gi
    storageClass: gp2

  datasources:
    datasources.yaml:
      apiVersion: 1
      deleteDatasources:
        - name: Prometheus
          orgId: 1
        - name: Loki
          orgId: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://monitoring-loki:3100
          access: proxy
          jsonData:
            maxLines: 1000
            timeout: 30

  adminUser: admin
  adminPassword: admin

loki:
  nameOverride: monitoring
  fullnameOverride: monitoring-loki
  enabled: true
  singleBinary:
    replicas: 1

  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

  persistence:
    enabled: true
    size: 5Gi
    storageClass: gp2

  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: filesystem

promtail:
  nameOverride: monitoring
  fullnameOverride: monitoring-promtail

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  config:
    clients:
      - url: http://monitoring-loki:3100/loki/api/v1/push
    snippets:
      extraRelabelConfigs:
        - action: replace
          replacement: dev-eks
          target_label: cluster
