kube-prometheus-stack:
  fullnameOverride: "monitoring"

  prometheusOperator:
    enabled: true
    tls:
      enabled: false
    webTLS:
      enabled: false
    tlsProxy:
      enabled: false
    admissionWebhooks:
      enabled: false
      certManager:
        enabled: false
      patch:
        enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 50m
        memory: 64Mi

  prometheus:
    enabled: true
    prometheusSpec:
      replicas: 1
    ingress:
      enabled: true
      ingressClassName: monitoring-nginx
      annotations:
        kubernetes.io/ingress.class: monitoring-nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
      paths:
        - /prometheus
      hosts:
        - ""

  grafana:
    enabled: true
    sidecar:
      dashboards:
        enabled: true
    service:
      port: 80
    ingress:
      enabled: true
      ingressClassName: monitoring-nginx
      annotations:
        kubernetes.io/ingress.class: monitoring-nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
      paths:
        - /grafana
      hosts:
        - ""
      labels: {}
      tls: []

  alertmanager:
    enabled: false
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: true
