kube-prometheus-stack:
  grafana:
    enabled: true
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
      hosts: 
        - grafana.local
      path: /
      pathType: Prefix

  prometheus:
    enabled: true
    prometheusSpec:
      retention: 15d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 8Gi
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 500m
          memory: 512Mi
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
      hosts: 
        - prometheus.local
      path: /
      pathType: Prefix

  alertmanager:
    enabled: true
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    ingress:
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: nginx
      hosts: 
        - alertmanager.local
      path: /
      pathType: Prefix

  nodeExporter:
    enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

  kubeStateMetrics:
    enabled: true
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

  prometheusOperator:
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi