prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: false
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 64Mi

grafana:
  persistence:
    enabled: false
  service:
    type: LoadBalancer
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://grafana-prometheus-server
          isDefault: true
        - name: Loki
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          access: proxy
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards
  dashboards:
    default:
      loki-logs:
        url: https://grafana.com/api/dashboards/13639/revisions/1/download
        datasource: Loki
      k8s-logs:
        url: https://grafana.com/api/dashboards/15141/revisions/1/download
        datasource: Loki
