prometheus:
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  server:
    persistentVolume:
      enabled: false
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

grafana:
  persistence:
    enabled: false
  service:
    type: LoadBalancer
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server
          isDefault: true
