nameOverride: monitoring
fullnameOverride: monitoring

prometheus:
  server:
    persistentVolume:
      enabled: true
      size: 4Gi
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

grafana:
  persistence:
    type: pvc
    enabled: true
    size: 2Gi

  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://monitoring-prometheus-server
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://monitoring-loki.monitoring.svc.cluster.local:3100
          access: proxy

  adminUser: admin
  adminPassword: admin

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s/"
    auth:
      disable_login_form: false
    security:
      allow_embedding: true

loki:
  enabled: true
  singleBinary:
    replicas: 1
    extraArgs:
      - -memberlist.bind-addr=0.0.0.0:7946

  memberlist:
    enabled: false
    ringName: ingester

  service:
    port: 3100
    targetPort: http-metrics
    annotations: {}

  persistence:
    enabled: true
    size: 5Gi
    storageClass: gp2

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  loki:
    auth_enabled: false
    commonConfig:
      path_prefix: /data/loki
      replication_factor: 1
      storage:
        filesystem:
          chunks_directory: /data/loki/chunks
          rules_directory: /data/loki/rules

promtail:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

  config:
    clients:
      - url: http://monitoring-loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
    snippets:
      extraRelabelConfigs: []
