apiVersion: v1
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - access: proxy
      isDefault: true
      name: Prometheus
      type: prometheus
      url: http://monitoring-prometheus-server
    - access: proxy
      name: Loki
      type: loki
      url: http://monitoring-loki:3100
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [auth]
    disable_login_form = false
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [security]
    allow_embedding = true
    [server]
    domain = ''
    root_url = %(protocol)s://%(domain)s/
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"datasources.yaml":"apiVersion: 1\ndatasources:\n- access: proxy\n  isDefault: true\n  name: Prometheus\n  type: prometheus\n  url: http://monitoring-prometheus-server\n- access: proxy\n  name: Loki\n  type: loki\n  url: http://monitoring-loki:3100\n","grafana.ini":"[analytics]\ncheck_for_updates = true\n[auth]\ndisable_login_form = false\n[grafana_net]\nurl = https://grafana.net\n[log]\nmode = console\n[paths]\ndata = /var/lib/grafana/\nlogs = /var/log/grafana\nplugins = /var/lib/grafana/plugins\nprovisioning = /etc/grafana/provisioning\n[security]\nallow_embedding = true\n[server]\ndomain = ''\nroot_url = %(protocol)s://%(domain)s/\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"monitoring","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"grafana","app.kubernetes.io/version":"10.2.2","argocd.argoproj.io/instance":"monitoring","helm.sh/chart":"grafana-7.0.19"},"name":"monitoring-grafana","namespace":"monitoring"}}
  creationTimestamp: "2024-11-29T20:57:14Z"
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.2.2
    argocd.argoproj.io/instance: monitoring
    helm.sh/chart: grafana-7.0.19
  name: monitoring-grafana
  namespace: monitoring
  resourceVersion: "15491"
  uid: ab7ad1ad-ee25-4aaf-be60-62efbba49714
