velero:
  # Init container settings
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.9.2 # Plugin for AWS S3
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

  # Backup configuration
  configuration:
    backupStorageLocation:
      - name: default
        provider: aws
        # Using existing S3 bucket with prefix for velero
        bucket: alexsuff
        prefix: velero/${ENVIRONMENT}
        config:
          region: us-east-2
    volumeSnapshotLocation:
      - name: aws
        provider: aws
        config:
          region: us-east-2

  # Schedule daily backups at 3:30 AM
  schedules:
    full-cluster-backup:
      schedule: "30 3 * * *"
      template:
        ttl: "168h" # Keep backups for 7 days
        includedNamespaces:
          - "*"
        excludedNamespaces:
          - kube-system
        includeClusterResources: true
        storageLocation: default

  # Resource limits
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

  # Security context
  securityContext:
    fsGroup: 65534

  # Service account for AWS permissions
  serviceAccount:
    server:
      create: true
      name: velero
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::529088295850:role/${ENVIRONMENT}-velero-role

  # Metrics settings for monitoring
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
