replicaCount: 1

image:
  repository: jondaw/devops-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

livenessProbe:
  path: /api/status
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  path: /api/status
  initialDelaySeconds: 5
  periodSeconds: 10
