replicaCount: 1
image:
  repository: jondaw/devops-api
  tag: develop
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  path: /api/status
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  path: /api/status
  initialDelaySeconds: 5
  periodSeconds: 10

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000

