---
all:
  children:
    eks_workers:
      hosts:
        worker1:
          ansible_host: 10.0.1.1
        worker2:
          ansible_host: 10.0.1.2
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/eks-key.pem
