apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-svc
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "web.selectorLabels" . | nindent 4 }}
    