apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-develop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/devops-project.git
    targetRevision: develop
    path: helm/charts/api
    helm:
      valueFiles:
        - ../../environments/develop/values.yaml
        - values-develop.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
