apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: AppArmor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thejondaw/devops-project.git
    path: helm/charts/apparmor
    targetRevision: develop
    helm:
      valueFiles:
        - ../../environments/develop/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
