apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-promtail
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thejondaw/devops-project.git
    path: helm/charts/logging
    targetRevision: develop
    helm:
      values: |
        loki:
          enabled: true
          persistence:
            enabled: true
            size: "2Gi"
          config:
            auth_enabled: false
              limits_config:
                retention_period: 72h
            storage:
              type: local
          resources:
            requests:
               cpu: 50m
               memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        promtail:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
