apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thejondaw/devops-project.git
    path: helm/charts/vault
    targetRevision: develop
    helm:
      valueFiles:
        - ../../environments/develop/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
