---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    environment: develop
    service: vault
    managed-by: terraform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault
  annotations:
    eks.amazonaws.com/role-arn: ${VAULT_ROLE_ARN}
