apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    chart: velero
    repoURL: https://vmware-tanzu.github.io/helm-charts
    targetRevision: 8.3.0
    helm:
      values: |
        configuration:
          provider: aws
          backupStorageLocation:
            - name: aws
              provider: aws
              bucket: alexsuff
              config:
                region: us-east-2
          volumeSnapshotLocation:
            - name: aws
              provider: aws
              config:
                region: us-east-2
        credentials:
          useSecret: true
          secretContents:
            cloud: |
              [default]
              aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.7.0
            volumeMounts:
              - mountPath: /target
                name: plugins
        volumes:
          - name: plugins
            emptyDir: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: velero
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/thejondaw/devops-pet-project.git
#     path: helm/charts/velero
#     targetRevision: master
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: velero
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
