apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: vault-init
          image: hashicorp/vault:latest
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Wait for Vault to start
              sleep 10
              until vault status; do
                sleep 2
              done

              # Check if already initialized
              if ! vault status | grep -q "Initialized.*true"; then
                # Init vault and save root token
                vault operator init -format=json > /tmp/keys.json

                # Get unsealing keys and unseal
                for i in {0..2}; do
                  KEY=$(cat /tmp/keys.json | jq -r ".unseal_keys_b64[$i]")
                  vault operator unseal $KEY
                done

                # Login and configure
                vault login $(cat /tmp/keys.json | jq -r '.root_token')

                # Configure secrets & auth
                vault secrets enable -path=secret kv-v2
                vault auth enable kubernetes

                vault write auth/kubernetes/config \
                  kubernetes_host="https://kubernetes.default.svc"

                # Basic policy and role
                vault policy write api-policy - <<EOF
                path "secret/data/database" {
                  capabilities = ["read"]
                }
                EOF

                vault write auth/kubernetes/role/api \
                  bound_service_account_names=api-sa \
                  bound_service_account_namespaces=app \
                  policies=api-policy \
                  ttl=1h

                # Write DB creds
                vault kv put secret/database \
                  username="jondaw" \
                  password="password" \
                  dbname="devopsdb"
              fi
      restartPolicy: OnFailure
      serviceAccountName: vault
