apiVersion: v2
name: vault
description: HashiCorp Vault Helm chart
type: application
version: 0.1.0
dependencies:
  - name: vault
    repository: https://helm.releases.hashicorp.com
    version: 0.25.0
