vault:
  global:
    enabled: true
    tlsDisable: true

  injector:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  server:
    annotations:
      avp.kubernetes.io/path: "secret/data/vault"

    dataStorage:
      enabled: true
      size: 1Gi
      storageClass: "gp2"
      accessMode: ReadWriteOnce

    standalone:
      enabled: true
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "[::]:8200"
          cluster_address = "[::]:8201"
        }
        storage "file" {
          path = "/vault/data"
        }

        # Включаем Audit логи
        audit {
          enabled = true
          type    = "file"
          options = {
            file_path = "/vault/logs/audit.log"
          }
        }

    service:
      enabled: true
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      port: 8200

    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::529088295850:role/develop-vault-role

    extraEnvironmentVars:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_API_ADDR: "http://127.0.0.1:8200"
      VAULT_LOG_LEVEL: "debug"

  ui:
    enabled: true
    serviceType: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    externalPort: 8200
    targetPort: 8200

  csi:
    enabled: true
    daemonSet:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
