vault:
  server:
    affinity: ""
    ha:
      enabled: false

    dataStorage:
      size: 1Gi

    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"

    auditStorage:
      enabled: true
      size: 1Gi

    serviceAccount:
      create: false
      name: "vault"

    extraEnvironmentVars:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_API_ADDR: "http://127.0.0.1:8200"

  ui:
    enabled: true
    serviceType: LoadBalancer
    externalPort: 8200

  injector:
    enabled: true
    replicas: 1
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
