loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
  config:
    limits_config:
      retention_period: 72h
    compactor:
      retention_enabled: true
    ruler:
      storage:
        type: local
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

promtail:
  enabled: true
  config:
    snippets:
      extraScrapeConfigs: |
        - job_name: kubernetes-pods
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_annotation_prometheus_io_scrape
              action: keep
              regex: true
            - source_labels:
                - __meta_kubernetes_pod_container_name
              action: replace
              target_label: container_name
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
