apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-db-cm
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
