apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "api.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "api"
        vault.hashicorp.com/agent-inject-secret-database: "secret/data/database"
        vault.hashicorp.com/agent-inject-template-database: |
          {
            {{`{{- with secret "secret/data/database" -}}
            "DBUSER": "{{ .Data.data.username }}",
            "DB": "{{ .Data.data.dbname }}",
            "DBPASS": "{{ .Data.data.password }}"
            {{- end -}}`}}
            "DBHOST": "{{ .Values.database.host }}",
            "DBPORT": "{{ .Values.database.port }}"
          }
    spec:
      serviceAccountName: api-sa
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: "{{ .Values.service.targetPort }}"
