apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.username }}
  password: {{ .Values.database.password }}
  