{{- range $name, $profile := .Values.profiles }}
{{- if $profile.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apparmor-{{ $name }}-profile
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "apparmor.labels" $ | nindent 4 }}
    profile-type: {{ $name }}
data:
  profile: |
    #include <tunables/global>
    profile k8s-{{ $name }} flags=(attach_disconnected) {
      {{- range $profile.rules.network }}
      {{ . }}
      {{- end }}
      
      {{- range $profile.rules.file }}
      {{ . }}
      {{- end }}
      
      {{- range $profile.rules.capabilities }}
      {{ . }}
      {{- end }}
      
      # Common rules
      deny @{PROC}/{*,**^[0-9*],sys/kernel/shm*} wkx,
      deny @{PROC}/sysrq-trigger rwklx,
      deny @{PROC}/mem rwklx,
      deny @{PROC}/kmem rwklx,
    }
{{- end }}
{{- end }}
