apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: apparmor-loader
  labels: { { - include "apparmor.labels" . | nindent 4 } }
spec:
  selector:
    matchLabels: { { - include "apparmor.selectorLabels" . | nindent 6 } }
  template:
    metadata:
      labels: { { - include "apparmor.selectorLabels" . | nindent 8 } }
    spec:
      containers:
        - name: loader
          image: ubuntu:20.04
          command: ["/bin/sh", "-c"]
          args:
            - |
              apt-get update && apt-get install -y apparmor-utils
              while true; do
                for profile in /etc/apparmor.d/k8s-*; do
                  apparmor_parser -r "$profile"
                done
                sleep 60
              done
          securityContext:
            privileged: true
          volumeMounts:
            - name: profiles
              mountPath: /etc/apparmor.d
            - name: modules
              mountPath: /lib/modules
            - name: sys
              mountPath: /sys
      volumes:
        - name: profiles
          configMap:
            name: apparmor-profiles
        - name: modules
          hostPath:
            path: /lib/modules
        - name: sys
          hostPath:
            path: /sys
