aws-ebs-csi-driver:
  controller:
    nodeSelector:
      kubernetes.io/os: linux
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 5m
        memory: 20Mi
