apiVersion: v2
name: ingress-nginx
description: NGINX Ingress Controller
version: 0.1.0
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.9.0
