ingress-nginx:
  controller:
    resources:
      requests:
        cpu: 25m
        memory: 48Mi
      limits:
        cpu: 50m
        memory: 96Mi
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    metrics:
      enabled: true
