nameOverride: plg
fullnameOverride: plg

prometheus:
  nameOverride: plg
  fullnameOverride: plg-prometheus
  server:
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi

grafana:
  nameOverride: plg
  fullnameOverride: plg-grafana
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: http://plg-prometheus-server
          access: proxy
          isDefault: true
        - name: Loki
          type: loki
          url: http://plg-loki:3100
          access: proxy
          jsonData:
            maxLines: 1000
            timeout: 30

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ""
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards

loki:
  nameOverride: plg
  fullnameOverride: plg-loki
  enabled: true
  singleBinary:
    replicas: 1

  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp2

  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1

    storage:
      type: filesystem

    schema_config:
      configs:
        - from: "2023-01"
          store: filesystem
          object_store: filesystem
          schema: v12
          index:
            prefix: loki_index_
            period: 24h

    limits_config:
      retention_period: 72h
      ingestion_rate_mb: 4
      ingestion_burst_size_mb: 6

promtail:
  nameOverride: plg
  fullnameOverride: plg-promtail
  enabled: true
  config:
    clients:
      - url: http://plg-loki:3100/loki/api/v1/push

    snippets:
      pipelineStages:
        - docker: {}

  tolerations:
    - operator: Exists

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
