apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-repo-server
    spec:
      containers:
      - name: argocd-vault-plugin
        # Правильный образ из публичного регистри
        image: pratikdeoghare/argocd-vault-plugin-sidecar:v0.2.0
        command: [/var/run/argocd/argocd-cmp-server]
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
          - name: custom-tools
            mountPath: /usr/local/bin
          - name: plugins
            mountPath: /home/argocd/cmp-server/plugins
          - name: cmp-plugin
            mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-helm.yaml
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: plugins
          emptyDir: {}
        - name: cmp-plugin
          configMap:
            name: cmp-plugin
            items:
              - key: avp-helm.yaml
                path: avp-helm.yaml