api:
  replicaCount: 1
  image:
    tag: develop
  database:
    host: ""
    port: "5432"
    name: "devopsdb"
    username: "jondaw"
    password: "password"

web:
  replicaCount: 1
  image:
    tag: develop
  api:
    host: "http://develop-api-svc"

vault:
  server:
    serviceAccount:
      roleArn: "arn:aws:iam::529088295850:role/develop-vault-role"
