api:
  replicaCount: 1
  image:
    tag: develop
  database:
    host: "" # Will be populated by post-install script
    port: "5432"
    name: "devopsdb"
    username: "jondaw"
    password: "password"

web:
  replicaCount: 1
  image:
    tag: develop
  api:
    host: "http://develop-api-svc" # Points to API service in develop namespace
