api:
  replicaCount: 1
  image:
    tag: develop
  database:
    host: ""
    port: "5432"
    name: "devopsdb"
    username: "jondaw"
    password: "password"

web:
  replicaCount: 1
  image:
    tag: develop
  api:
    host: "http://develop-api-svc"

monitoring:
  grafana:
    ingress:
      hosts:
        - grafana.develop.local
  prometheus:
    ingress:
      hosts:
        - prometheus.develop.local
  alertmanager:
    ingress:
      hosts:
        - alertmanager.develop.local

vault:
  server:
    serviceAccount:
      roleArn: "arn:aws:iam::ACCOUNT_ID:role/develop-vault-role"
