loki:
  isDefault: true
  singleBinary:
    replicas: 1

  monitoring:
    serviceMonitor:
      enabled: true
      metricsInstance:
        enabled: true

  persistence:
    enabled: true
    storageClass: gp2
    size: 10Gi

  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1

    storage:
      type: filesystem

    limits_config:
      retention_period: 72h
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_entries_limit_per_query: 5000

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info

    storage_config:
      hedging:
        at: 250ms
        max_per_second: 20
      aws:
        bucketnames: ""
      filesystem:
        directory: /var/loki/chunks

    schema_config:
      configs:
        - from: "2023-01"
          store: boltdb-shipper
          object_store: filesystem
          schema: v12
          index:
            prefix: loki_index_
            period: 24h

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
