loki:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: gp2

  auth_enabled: false

  server:
    http_listen_port: 3100
    grpc_listen_port: 9095

  memberlist:
    join_members:
      - loki-memberlist

  ingester:
    lifecycler:
      ring:
        replication_factor: 1
    chunk_idle_period: 30m
    chunk_retain_period: 1m

  schemaConfig:
    configs:
      - from: 2023-01-01
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /data/loki/index
      cache_location: /data/loki/cache
      cache_ttl: 24h
      shared_store: filesystem
    filesystem:
      directory: /data/loki/chunks

  limits_config:
    retention_period: 72h
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    max_entries_limit_per_query: 5000

  serviceMonitor:
    enabled: true
    interval: 30s

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
