loki:
  singleBinary:
    replicas: 1

  monitoring:
    serviceMonitor:
      enabled: true

  persistence:
    enabled: true
    storageClass: gp2
    size: 10Gi

  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    storage:
      type: filesystem

    limits_config:
      retention_period: 72h
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 4
      ingestion_burst_size_mb: 6

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      log_level: info

    storage_config:
      filesystem:
        directory: /var/loki/chunks

    schema_config:
      configs:
        - from: "2023-01"
          store: filesystem
          object_store: filesystem
          schema: v12
          index:
            prefix: loki_index_
            period: 24h

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
