name: CD - Infrastructure Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to destroy"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - stage
          - prod

env:
  TF_STATE_BUCKET: "alexsuff"
  AWS_REGION: "us-east-2"

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Destroy RDS
        run: |
          cd terraform/modules/rds
          terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=${{ github.event.inputs.environment }}/rds.tfstate" -backend-config="region=${{ env.AWS_REGION }}"
          terraform destroy -auto-approve -var-file=../../environments/${{ github.event.inputs.environment }}/terraform.tfvars

      - name: Destroy EKS
        run: |
          cd terraform/modules/eks
          terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=${{ github.event.inputs.environment }}/eks.tfstate" -backend-config="region=${{ env.AWS_REGION }}"
          terraform destroy -auto-approve -var-file=../../environments/${{ github.event.inputs.environment }}/terraform.tfvars

      - name: Destroy VPC
        run: |
          cd terraform/modules/vpc
          terraform init -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" -backend-config="key=${{ github.event.inputs.environment }}/vpc.tfstate" -backend-config="region=${{ env.AWS_REGION }}"
          terraform destroy -auto-approve -var-file=../../environments/${{ github.event.inputs.environment }}/terraform.tfvars