name: CD - Infrastructure Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - stage
          - prod
      action:
        description: "Action to perform"
        required: true
        type: choice
        options:
          - apply
          - destroy
        default: "apply"
  push:
    branches: ["master", "stage", "develop"]
    paths:
      # Infrastructure related changes
      - "terraform/modules/backend/**"
      - "terraform/modules/vpc/**"
      - "terraform/modules/eks/**"
      - "terraform/modules/rds/**"
      - "terraform/modules/tools/**"
      - "terraform/environments/**/*.tfvars"
      - ".github/workflows/cd-infrastructure.yaml"
      # Configuration files
      - "terraform/environments/develop/main.tf"
      - "terraform/environments/stage/main.tf"
      - "terraform/environments/prod/main.tf"
      - "Makefile"

env:
  AWS_REGION: "us-east-2"
  TF_BACKEND_BUCKET: "alexsuff"
  TF_BACKEND_DYNAMODB: "alexsuff-locks"

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Backend Deployment first
      - name: Deploy Backend
        if: github.event.inputs.action != 'destroy'
        run: |
          cd terraform/modules/backend
          terraform init
          terraform plan -var-file=../../environments/${{ github.event.inputs.environment || github.ref_name }}/terraform.tfvars -out=plan.tfplan
          terraform apply -auto-approve plan.tfplan

      # VPC Deployment
      - name: Deploy VPC
        if: success() && (github.event.inputs.action != 'destroy')
        run: |
          aws dynamodb delete-item \
          --table-name alexsuff-locks \
          --key '{"LockID": {"S": "environments/develop/vpc.tfstate"}}'

          cd terraform/modules/vpc
          terraform init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=environments/${{ github.event.inputs.environment || github.ref_name }}/vpc.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_BACKEND_DYNAMODB }}"

          terraform plan -var-file=../../environments/${{ github.event.inputs.environment || github.ref_name }}/terraform.tfvars -out=plan.tfplan
          terraform apply -auto-approve plan.tfplan

      # EKS Deployment
      - name: Deploy EKS
        if: success() && (github.event.inputs.action != 'destroy')
        run: |
          aws dynamodb delete-item \
          --table-name alexsuff-locks \
          --key '{"LockID": {"S": "environments/develop/eks.tfstate"}}'

          cd terraform/modules/eks
          terraform init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=environments/${{ github.event.inputs.environment || github.ref_name }}/eks.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_BACKEND_DYNAMODB }}"

          terraform plan -var-file=../../environments/${{ github.event.inputs.environment || github.ref_name }}/terraform.tfvars -out=plan.tfplan
          terraform apply -auto-approve plan.tfplan

      # RDS Deployment
      - name: Deploy RDS
        if: success() && (github.event.inputs.action != 'destroy')
        run: |
          aws dynamodb delete-item \
          --table-name alexsuff-locks \
          --key '{"LockID": {"S": "environments/develop/rds.tfstate"}}'
          
          cd terraform/modules/rds
          terraform init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=environments/${{ github.event.inputs.environment || github.ref_name }}/rds.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_BACKEND_DYNAMODB }}"

          terraform plan -var-file=../../environments/${{ github.event.inputs.environment || github.ref_name }}/terraform.tfvars -out=plan.tfplan
          terraform apply -auto-approve plan.tfplan

      # Tools Deployment (last in creation)
      - name: Deploy Tools
        if: success() && (github.event.inputs.action != 'destroy')
        run: |
          cd terraform/modules/tools
          terraform init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=environments/${{ github.event.inputs.environment || github.ref_name }}/tools.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_BACKEND_DYNAMODB }}"

          terraform plan -var-file=../../environments/${{ github.event.inputs.environment || github.ref_name }}/terraform.tfvars -out=plan.tfplan
          terraform apply -auto-approve plan.tfplan

      # Tools Destruction (first in destruction)
      - name: Destroy Tools
        if: github.event.inputs.action == 'destroy'
        run: |
          cd terraform/modules/tools
          terraform init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=environments/${{ github.event.inputs.environment }}/tools.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_BACKEND_DYNAMODB }}"
          terraform destroy -auto-approve -var-file=../../environments/${{ github.event.inputs.environment }}/terraform.tfvars

      # Reverse order for destruction
      - name: Destroy RDS
        if: success() && github.event.inputs.action == 'destroy'
        run: |
          cd terraform/modules/rds
          terraform init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=environments/${{ github.event.inputs.environment }}/rds.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_BACKEND_DYNAMODB }}"
          terraform destroy -auto-approve -var-file=../../environments/${{ github.event.inputs.environment }}/terraform.tfvars

      - name: Destroy EKS
        if: success() && github.event.inputs.action == 'destroy'
        run: |
          cd terraform/modules/eks
          terraform init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=environments/${{ github.event.inputs.environment }}/eks.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_BACKEND_DYNAMODB }}"
          terraform destroy -auto-approve -var-file=../../environments/${{ github.event.inputs.environment }}/terraform.tfvars

      - name: Destroy VPC
        if: success() && github.event.inputs.action == 'destroy'
        run: |
          cd terraform/modules/vpc
          terraform init \
            -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" \
            -backend-config="key=environments/${{ github.event.inputs.environment }}/vpc.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_BACKEND_DYNAMODB }}"
          terraform destroy -auto-approve -var-file=../../environments/${{ github.event.inputs.environment }}/terraform.tfvars

      # Finally destroy backend
      - name: Destroy Backend
        if: success() && github.event.inputs.action == 'destroy'
        run: |
          cd terraform/modules/backend
          terraform init
          terraform destroy -auto-approve -var-file=../../environments/${{ github.event.inputs.environment }}/terraform.tfvars
