name: EKS Module - Create

on:
  workflow_dispatch:
  push:
    branches: [ "master", "stage", "develop" ]
    paths:
      - 'terraform/modules/eks/**'
      - 'terraform/environments/develop/terraform.tfvars'
      - 'Makefile'
      - '.github/workflows/eks-module-create.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init EKS
        run: make init-eks

      - name: Terraform Plan EKS
        run: make plan-eks

      - name: Terraform Apply EKS
        run: make apply-eks
