name: CD - Destroy EKS

# - Trigger workflow ONLY on manual dispatch
# - Push to main branches with changes in VPC related files
on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
    paths:
      - 'terraform/modules/eks/**'
      - 'terraform/environments/develop/terraform.tfvars'
      - 'Makefile'
      - '.github/workflows/eks-module-destroy.yaml'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup AWS credentials for Terraform
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform working directory for EKS
      - name: Terraform Init EKS
        run: make init-eks

      # Destroy EKS Module
      - name: Terraform Destroy EKS
        run: make destroy-eks
