name: CD - Destroy RDS

# Trigger workflow on:
# - Manual dispatch from GitHub Actions UI (primary trigger for controlled destruction)
# - Push to main branches with changes in RDS related files
on:
  workflow_dispatch:
  push:
    branches: ["master", "stage", "develop"]
    paths:
      - "terraform/modules/rds/**"
      - "terraform/environments/develop/terraform.tfvars"
      - "Makefile"
      - ".github/workflows/rds-module-destroy.yaml"

jobs:
  # Infrastructure destruction job
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup AWS credentials for Terraform
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform working directory
      - name: Terraform Init RDS
        run: make init-rds

      # Initialize Terraform Plan
      - name: Terraform Plan RDS
        run: make plan-rds

      # Safety delay with warning message
      - name: Warning
        run: |
          echo "⚠️ WARNING: RDS WILL BE DESTROYED ⚠️"

      # Destroy RDS infrastructure
      - name: Terraform Destroy RDS
        run: make destroy-rds
