name: VPC Module - Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        type: boolean
        description: '⚠️ Check to confirm VPC destruction'
        required: true
      environment:
        type: choice
        description: 'Select environment'
        required: true
        options:
          - develop
          - stage

jobs:
  destroy:
    if: github.event.inputs.confirm_destroy == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: make init-vpc

      - name: Terraform Plan Destroy
        run: make plan-vpc

      - name: Confirm Destruction
        run: |
          echo "⚠️ WARNING: VPC DESTRUCTION INITIATED ⚠️"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Waiting 10 seconds before destruction..."
          sleep 10

      - name: Terraform Destroy
        run: make destroy-vpc