name: VPC Module - Destroy

on:
#  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init VPC
        run: make init-vpc

      - name: Terraform Plan Destroy VPC
        run: make plan-vpc

      - name: Warning
        run: |
          echo "⚠️ WARNING: VPC WILL BE DESTROYED IN 10 SECONDS ⚠️"
          sleep 10

      - name: Terraform Destroy VPC
        run: make destroy-vpc