# Workflow name - Create VPC infrastructure using Terraform
name: VPC Module - Create

# Trigger workflow on:
# - Manual dispatch from GitHub Actions UI
# - Push to main branches with changes in VPC related files
on:
  workflow_dispatch:
    paths:
      - 'terraform/modules/vpc/**'
      - 'terraform/environments/develop/terraform.tfvars'
      - 'Makefile'
      - '.github/workflows/vpc-module-create.yaml'
#  push:
#    branches: [ "develop" ]
#    paths:
#      - 'terraform/modules/vpc/**'
#      - 'terraform/environments/develop/terraform.tfvars'
#      - 'Makefile'
#      - '.github/workflows/vpc-module-create.yaml'

jobs:
  # Infrastructure deployment job
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup AWS credentials for Terraform
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform working directory
      - name: Terraform Init VPC
        run: make init-vpc

      # Plan Terraform changes
      - name: Terraform Plan VPC
        run: make plan-vpc

      # Apply Terraform changes
      - name: Terraform Apply VPC
        run: make apply-vpc